Document: etbe-base
Title: Debian etbe-base Manual
Author: <insert document author here>
Abstract: This manual describes what etbe-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/etbe-base/etbe-base.sgml.gz

Format: postscript
Files: /usr/share/doc/etbe-base/etbe-base.ps.gz

Format: text
Files: /usr/share/doc/etbe-base/etbe-base.text.gz

Format: HTML
Index: /usr/share/doc/etbe-base/html/index.html
Files: /usr/share/doc/etbe-base/html/*.html
