Document: etbe-kvm
Title: Debian etbe-kvm Manual
Author: <insert document author here>
Abstract: This manual describes what etbe-kvm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/etbe-kvm/etbe-kvm.sgml.gz

Format: postscript
Files: /usr/share/doc/etbe-kvm/etbe-kvm.ps.gz

Format: text
Files: /usr/share/doc/etbe-kvm/etbe-kvm.text.gz

Format: HTML
Index: /usr/share/doc/etbe-kvm/html/index.html
Files: /usr/share/doc/etbe-kvm/html/*.html
