Document: etbe-mon
Title: Debian etbe-mon Manual
Author: <insert document author here>
Abstract: This manual describes what etbe-mon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/etbe-mon/etbe-mon.sgml.gz

Format: postscript
Files: /usr/share/doc/etbe-mon/etbe-mon.ps.gz

Format: text
Files: /usr/share/doc/etbe-mon/etbe-mon.text.gz

Format: HTML
Index: /usr/share/doc/etbe-mon/html/index.html
Files: /usr/share/doc/etbe-mon/html/*.html
