
all:


install:
	mkdir -p $(DESTDIR)/usr/share/keyrings
	install key/* $(DESTDIR)/usr/share/keyrings
	mkdir -p $(DESTDIR)/usr/sbin
	install sbin/* $(DESTDIR)/usr/sbin
	mkdir -p $(DESTDIR)/etc/bash.etbe
	install bash.etbe/* $(DESTDIR)/etc/bash.etbe
