#!/bin/bash
set -e

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt 0.12; then
  /usr/bin/systemctl restart sshd.service
fi

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt 0.3.10; then
  /usr/sbin/etbe-base-fix-unattended-upgrades
fi
